export default {
  artwork_time_01: require('../../assets/artwork_time_01.png'),
  artwork_time_02: require('../../assets/artwork_time_02.png'),
  autosalary_img_01: require('../../assets/autosalary_img_01.png'),
  autosalary_img_02: require('../../assets/autosalary_img_02.png'),
  autosalary_img_03: require('../../assets/autosalary_img_03.png'),
  free_img_01: require('../../assets/free_img_01.png'),
  free_img_02: require('../../assets/free_img_02.png'),
  free_img_03: require('../../assets/free_img_03.png'),
  free_img_04: require('../../assets/free_img_04.png'),
  img_wifi: require('../../assets/img_wifi.png'),
  plus_img_01: require('../../assets/plus_img_01.png'),
  plus_img_02: require('../../assets/plus_img_02.png'),
  plus_img_03: require('../../assets/plus_img_03.png'),
  push_message: require('../../assets/push_message.png'),
  search_store: require('../../assets/search_store.png'),
  slide_img_1: require('../../assets/slide_img_1.png'),
  upselling_banner1: require('../../assets/upselling_banner1.png'),
  upselling_banner2: require('../../assets/upselling_banner2.png'),
  upselling_banner3: require('../../assets/upselling_banner3.png'),
  xls: require('../../assets/xls.png'),
};
